language: python
python:
  - "3.6"
services:
  - postgresql

addons:
  postgresql: "9.6"

before_script:
  - psql -c 'CREATE DATABASE woodys_platform;' -U postgres
  - psql -c 'CREATE EXTENSION "uuid-ossp";' -U postgres

install: "pip install -r requirements.txt"
# command to run tests
script: "python test.py"