language: python
python:
  - "3.6"
services:
  - postgresql

before_script:
  - psql -c 'create database woodys_platform;' -U postgres
  - psql -c 'CREATE USER theobouwman WITH PASSWORD "sol2.Loa"';
  - psql -c 'GRANT ALL PRIVILEGES ON DATABASE "woodys_platform" to theobouwman';

install: "pip install -r requirements.txt"
# command to run tests
script: "python test.py"