language: python
python:
  - "3.6"
services:
  - postgresql

before_script:
  - psql -c 'CREATE EXTENSION IF NOT EXISTS "uuid-ossp";' -U postgres
  - psql -c 'CREATE DATABASE woodys_platform;' -U postgres

install: "pip install -r requirements.txt"
# command to run tests
script: "python test.py"